version: '3.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1305
      MYSQL_DATABASE: mercado
    ports:
      - "3307:3306"  # Mapeia a porta 3306 do container para a porta 3307 do host
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1305
      DB_NAME: mercado
